Install gfortran from scipy's solution

diff --git a/.github/workflows/publish_pypi.yml b/.github/workflows/publish_pypi.yml
--- a/.github/workflows/publish_pypi.yml
+++ b/.github/workflows/publish_pypi.yml
@@ -157,6 +157,8 @@ jobs:
       - name: Build wheels on macOS
         shell: bash
         run: |
+            set -e -x
+
             # Set LLVM-OpenMP URL
             if [[ $(uname -m) == "x86_64" ]]; then
               OPENMP_URL="https://anaconda.org/conda-forge/llvm-openmp/11.1.0/download/osx-64/llvm-openmp-11.1.0-hda6cdc1_1.tar.bz2"
@@ -164,7 +166,50 @@ jobs:
               OPENMP_URL="https://anaconda.org/conda-forge/llvm-openmp/11.1.0/download/osx-arm64/llvm-openmp-11.1.0-hf3c4609_1.tar.bz2"
             fi
 
-            # Can't download directly, use conda/mamba and set environment variables
+            # Download gfortran with proper macOS minimum version (11.0)
+            if [[ $(uname -m) == "x86_64" ]]; then
+              GFORTRAN_URL="https://github.com/isuruf/gcc/releases/download/gcc-11.3.0-2/gfortran-darwin-x86_64-native.tar.gz"
+              KNOWN_SHA256="981367dd0ad4335613e91bbee453d60b6669f5d7e976d18c7bdb7f1966f26ae4 gfortran.tar.gz"
+            elif [[ $(uname -m) == "arm64" ]]; then
+              GFORTRAN_URL="https://github.com/isuruf/gcc/releases/download/gcc-11.3.0-2/gfortran-darwin-arm64-native.tar.gz"
+              KNOWN_SHA256="84364eee32ba843d883fb8124867e2bf61a0cd73b6416d9897ceff7b85a24604 gfortran.tar.gz"
+            fi
+
+            # Validate gfortran tarball
+            curl -L $GFORTRAN_URL -o gfortran.tar.gz
+            if ! echo "$KNOWN_SHA256" != "$(shasum --algorithm 256 gfortran.tar.gz)"; then
+              echo "Checksum failed"
+              exit 1
+            fi
+
+            mkdir -p gfortran_installed
+            tar -xv -C gfortran_installed/ -f gfortran.tar.gz
+
+            export FC=$(pwd)/gfortran_installed/gfortran-darwin-arm64-native/bin/gfortran
+            export PATH=$(pwd)/gfortran_installed/gfortran-darwin-arm64-native/bin:$PATH
+
+            # link libgfortran dylibs and place them in $HOME/.local/lib
+            # and then change rpath to $HOME/.local/lib for each of them
+            mkdir -p $HOME/.local/lib
+            if [[ $(uname -m) == "x86_64" ]]; then
+              lib_dir=$(pwd)/gfortran_installed/gfortran-darwin-x86_64-native/lib
+              for lib in libgfortran.5.dylib libgfortran.dylib libquadmath.0.dylib libquadmath.dylib libgcc_s.1.dylib libgcc_s.1.1.dylib; do
+                cp $lib_dir/$lib $HOME/.local/lib/
+                install_name_tool -id $HOME/.local/lib/$lib $HOME/.local/lib/$lib
+                codesign --force --sign - $HOME/.local/lib/$lib
+              done
+            elif [[ $(uname -m) == "arm64" ]]; then
+              lib_dir=$(pwd)/gfortran_installed/gfortran-darwin-arm64-native/lib
+              for lib in libgfortran.5.dylib libgfortran.dylib libquadmath.0.dylib libquadmath.dylib libgcc_s.1.1.dylib; do
+                cp $lib_dir/$lib $HOME/.local/lib/
+                install_name_tool -id $HOME/.local/lib/$lib $HOME/.local/lib/$lib
+                codesign --force --sign - $HOME/.local/lib/$lib
+              done
+            fi
+
+            export SDKROOT=${SDKROOT:-$(xcrun --show-sdk-path)}
+
+            # Can't download LLVM-OpenMP directly, use conda/mamba and set environment variables
             brew install miniforge
             mamba create -n pybamm-dev $OPENMP_URL
             if [[ $(uname -m) == "x86_64" ]]; then
@@ -185,7 +230,8 @@ jobs:
           CIBW_ARCHS_MACOS: auto
           CIBW_BEFORE_BUILD: python -m pip install cmake casadi setuptools wheel delocate
           CIBW_REPAIR_WHEEL_COMMAND: delocate-listdeps {wheel} && delocate-wheel -v -w {dest_dir} {wheel}
-          CIBW_TEST_COMMAND: python -c "import pybamm; pybamm.IDAKLUSolver()"
+          CIBW_TEST_EXTRAS: "dev,all"
+          CIBW_TEST_COMMAND: pytest {package}/tests/integration/
 
       - name: Upload wheels for macOS (amd64, arm64)
         uses: actions/upload-artifact@v4
